name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.0
    - name: Use Node.js 22
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '22'
        cache: 'npm'
    - run: npm install
    - run: npm test

  sonarcloud:
    name: Run SonarCloud
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.0
    - uses: actions/setup-node@v3.5.0
      with:
        node-version: '22'
        cache: 'npm'
    - run: npm install
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

